### PR TITLE
Perform an integrity check against the opened database

### PR DESCRIPTION
**Pull request by percyserato**
Perform an integrity check against the opened database using "PRAGMA integrity_check" command, if there is any error found then we attempt to remove the corrupt database and recreate a new one and we prevent GAI using a corrupt database.

### CODE REVIEW

**Comment by maxime-viargues-serato** [comment]
I have worked on this so I can't rely check what you are doing. I think Steve worked on it.
However you are mixing tabs and spaces, the original was using spaces I believe.

**Comment by percyserato** [comment]
Hi Maxime, thanks and my Xcode was set to match the current coding standard which prefers tabs. This is a fork so that's why it's using spaces, should not be a problem I reckon. :-)

**Comment by hoseking-serato** [comment]
Looks like this will work man. Might need to update the documentation for `open()` as its doing a little more that open now. Another option would be to keep the interface to `DataStoreSqlite` simple (`open(), isOpen(), integrityCheck()`) and perform higher level logic in the caller. Just an option though.

**Comment by percyserato** [comment]
Hi Steve, yes it does work and I've tested it multiple times. I considered the option you are saying and it's a bit tricky as the **open()** method gets called in the **constructor of Analytics** and we will need to spend more time to tidy up the code. I will update the documentation for **open()** and amend those tabs to spaces to match the original code base style.

**Comment by hoseking-serato** [comment]
Awesome man that sounds like a good approach +1

**Pull request merged**
